apiVersion: v2
name: nginx-chart
description: A Helm chart for my Kubernetes
icon: https://img.icons8.com/fluency/48/null/play-station--v2.png
type: application
version: 0.1.4
appVersion: "1.16.0"
maintainers:
- email: chago19911@gmail.com
  name: kube.silknet.com
