

replicaCount: 1

images:
  - name: registry.silknet.com/dchaganava/docker-nginx-php-fpm/nginx
    tag: 0.1
  - name: registry.silknet.com/dchaganava/docker-nginx-php-fpm
    tag: latest
  - name: memcached
    tag: alpine
  - name: redis
    tag: alpine
    pullPolicy: Always

service:
  nginx:
    name: my-service-nginx
    selector:
      app: nginx
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 80
      - name: https
        protocol: TCP
        port: 8443
        targetPort: 443

  php:
    name: php-fpm-service
    selector:
      app: php-fpm
    ports:
      - name: cgi
        protocol: TCP
        port: 9000
        targetPort: 9000

  redis:
    name: redis
    selector:
      app: redis
    ports:
      - name: redis
        port: 6379
        targetPort: 6379

  memcached:
    name: memcached
    selector:
      app: memcached
    ports:
      - name: memcached
        port: 11211
        targetPort: 11211

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "1m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120s"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: Deny";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      more_set_headers "X-Content-Type-Options: nosniff";
      add_header X-Content-Type-Options nosniff;
      add_header X-Frame-Options SAMEORIGIN;
      add_header X-XSS-Protection "1; mode=block";
  host: kube2.silknet.com
  secretName: my-secret
  path: /
  pathType: ImplementationSpecific
  servicePort: 8080
