apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kube-clinic-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            defaultMode: 0777
      containers:
      - name: nginx
        image: {{ index .Values.images 0 "name" }}:{{ index .Values.images 0 "tag" }}
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        ports:
        - containerPort: 80
      - name: php-fpm
        image: {{ index .Values.images 1 "name" }}:{{ index .Values.images 1 "tag" }}
        ports:
        - containerPort: 9000
      - name: memcached
        image: {{ index .Values.images 2 "name" }}:{{ index .Values.images 2 "tag" }}
        ports:
        - containerPort: 11211
      - name: redis
        image: {{ index .Values.images 3 "name" }}:{{ index .Values.images 3 "tag" }}
        ports:
        - containerPort: 6379
