apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: {{ index .Values.service.nginx.ports 0 "port" }}
      targetPort: {{ index .Values.service.nginx.ports 0 "targetPort" }}
    - name: https
      protocol: TCP
      port: {{ index .Values.service.nginx.ports 1 "port" }}
      targetPort: {{ index .Values.service.nginx.ports 1 "targetPort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-php-fpm-service
spec:
  selector:
    app: my-app
  ports:
  - name: cgi
    protocol: TCP
    port: {{ index .Values.service.php.ports 0 "port" }}
    targetPort: {{ index .Values.service.php.ports 0 "targetPort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    app: my-app
  ports:
  - name: redis
    port: {{index .Values.service.redis.ports 0 "port" }}
    targetPort: {{ index .Values.service.redis.ports 0 "targetPort" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached
spec:
  selector:
    app: my-app
  ports:
  - name: memcached
    port: {{ index .Values.service.memcached.ports 0 "port" }}
    targetPort: {{ index .Values.service.memcached.ports 0 "targetPort" }}
